# Site Info
title: 宜宾市第三中学大观校区
SEOTitle: 南溪五中(宜宾三中大观校区) | Nanxi No.5 Middle School (Yibin No.3 Middle School Daguan Campus)
header-img: img/home-bg.jpg
email: MFCJ45681@outlook.com
description: "这里是宜宾三中大观校区（原南溪五中）的官网，与你一起发现更大的世界"
keywords: "宜宾三中大观校区, ybszdgxq, Nanxi No.5 Middle School, Yibin No.3 Middle School Daguan Campus, 学校官网"
url: "https://huangxuan.me"  # 替换为实际域名
baseurl: "" 

# Content Settings
future: true
permalink: pretty
paginate: 10
exclude: 
  - "less"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"
  - "README.zh.md"

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span: 
      line_numbers: false
    block: 
      line_numbers: true
      start_line: 1

# Social Accounts (示例)
weibo_username: school_weibo
zhihu_username: school_zhihu
github_username: school_github

# Features
anchorjs: true
sidebar: true
featured-tags: true
featured-condition-size: 1

# Analytics (示例)
google_analytics: UA-XXXXXX-X

# Sidebar Content
sidebar-about-description: "宜宾市重点中学 | 省级示范高中"
sidebar-avatar: /assets/img/school-logo.png  # 替换为实际路径

# Comments (可选)
disqus_username: your-disqus-shortname  # 替换为实际Disqus账号

# Friends Links
friends:
  - title: "宜宾市招生考试网"
    href: "https://www.ybzsb.cn"
  - title: "四川省教育考试院"
    href: "http://www.sceea.cn/"
  - title: "中国教育部"
    href: "http://www.moe.gov.cn/"
